#!/bin/bash
set -euo pipefail

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
RED='\033[0;31m'
NC='\033[0m' # No Color

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
AGENTS_FILE="$SCRIPT_DIR/AGENTS.md"

# External skills are managed from normal source clones under ~/dev. Each entry:
# name|repo_path|skill_relative_path|install_command
# install_command runs from repo_path. Leave it empty when no extra install step
# is needed.
TURBO_REVIEW_INSTALL_COMMAND="bash \"$SCRIPT_DIR/installers/turbo-review.sh\""
EXTERNAL_SKILLS=(
  "turbo-review|$HOME/dev/gitlab-master/achristensen/kungfu|turbo-review|$TURBO_REVIEW_INSTALL_COMMAND"
)

# Function to link the consolidated AGENTS.md file
link_agents_file() {
  local destination="$1"

  echo -e "\n${GREEN}Linking $(basename "$destination")...${NC}"

  if [ ! -f "$AGENTS_FILE" ]; then
    echo -e "${RED}Error: $AGENTS_FILE not found${NC}"
    exit 1
  fi

  mkdir -p "$(dirname "$destination")"
  ln -sfn "$AGENTS_FILE" "$destination"
  echo -e "${GREEN}✓ Linked $destination -> $AGENTS_FILE${NC}"
}

# Function to remove legacy per-agent instruction files
remove_legacy_agent_file() {
  local path="$1"
  local first_line

  if [ ! -e "$path" ] && [ ! -L "$path" ]; then
    return 0
  fi

  if [ -L "$path" ]; then
    rm -f "$path"
    echo -e "${GREEN}✓ Removed legacy symlink $path${NC}"
    return 0
  fi

  if [ -f "$path" ]; then
    IFS= read -r first_line <"$path" || first_line=""
    case "$first_line" in
      "# Claude Code Configuration" | "# AmpCode Configuration")
        rm -f "$path"
        echo -e "${GREEN}✓ Removed generated legacy file $path${NC}"
        return 0
        ;;
    esac
  fi

  echo -e "${YELLOW}Leaving $path in place; it does not look generated by this repo${NC}"
}

# Function to link settings files
link_settings() {
  local tool="$1"
  local settings_file="$2"

  local repo_settings="$SCRIPT_DIR/settings/$tool.json"

  echo -e "\n${GREEN}$tool settings configuration...${NC}"

  if [ -L "$settings_file" ]; then
    if [ "$(readlink "$settings_file")" = "$repo_settings" ]; then
      echo -e "${GREEN}✓ Settings already linked${NC}"
    else
      ln -sfn "$repo_settings" "$settings_file"
      echo -e "${GREEN}✓ Relinked settings${NC}"
    fi
  elif [ -f "$settings_file" ]; then
    echo -e "${YELLOW}Existing settings.json found${NC}"
    echo -e "${YELLOW}Review $repo_settings for recommended settings${NC}"
    echo -e "${YELLOW}Run ${BLUE}rm $settings_file${NC} to remove the existing settings${NC}"
    exit 1
  else
    # Create destination directory if it doesn't exist
    mkdir -p "$(dirname "$settings_file")"
    ln -s "$repo_settings" "$settings_file"
    echo -e "${GREEN}✓ Linked settings${NC}"
  fi
}

# Function to merge settings from template into existing config
merge_settings() {
  local tool="$1"
  local config_file="$2"

  local repo_settings="$SCRIPT_DIR/settings/$tool.json"

  echo -e "\n${GREEN}$tool configuration...${NC}"

  if [ ! -f "$repo_settings" ]; then
    echo -e "${YELLOW}No settings template found for $tool${NC}"
    return 0
  fi

  if [ ! -f "$config_file" ]; then
    echo -e "${YELLOW}Config file $config_file not found, creating from template${NC}"
    mkdir -p "$(dirname "$config_file")"
    cp "$repo_settings" "$config_file"
    echo -e "${GREEN}✓ Created config from template${NC}"
  else
    echo -e "${YELLOW}Merging settings into existing config${NC}"

    # Use jq to merge the repo settings into the existing config
    # The + operator merges objects, with the right side taking precedence
    if command -v jq >/dev/null 2>&1; then
      local temp_file; temp_file=$(mktemp)
      jq -s '.[0] * .[1]' "$config_file" "$repo_settings" > "$temp_file" && mv "$temp_file" "$config_file"
      echo -e "${GREEN}✓ Merged settings${NC}"
    else
      echo -e "${RED}jq not available - cannot merge settings automatically${NC}"
      echo -e "${YELLOW}Manual merge required: $repo_settings -> $config_file${NC}"
    fi
  fi
}

link_skill() {
  local name="$1"
  local skill_path="$2"
  local destination_root="$3"
  local destination="$destination_root/$name"

  mkdir -p "$destination_root"

  if [ -L "$destination" ]; then
    rm -f "$destination"
  elif [ -e "$destination" ]; then
    echo -e "${YELLOW}Skipping $destination; it exists and is not a symlink${NC}"
    return 0
  fi

  ln -s "$skill_path" "$destination"
  echo -e "${GREEN}✓ Linked $destination -> $skill_path${NC}"
}

run_skill_install_command() {
  local name="$1"
  local repo_path="$2"
  local install_command="$3"

  if [ -z "$install_command" ]; then
    return 0
  fi

  echo -e "${GREEN}Running $name install command...${NC}"
  if (cd "$repo_path" && bash -eu -o pipefail -c "$install_command"); then
    echo -e "${GREEN}✓ Ran $name install command${NC}"
  else
    echo -e "${YELLOW}Install command failed for $name; skill symlinks were still created${NC}"
  fi
}

install_external_skills() {
  local entry
  local name
  local repo_path
  local skill_relative_path
  local install_command
  local skill_path

  echo -e "\n${GREEN}Installing external skills...${NC}"

  for entry in "${EXTERNAL_SKILLS[@]}"; do
    IFS='|' read -r name repo_path skill_relative_path install_command <<<"$entry"

    if ! git -C "$repo_path" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
      echo -e "${YELLOW}Skipping $name; clone not found at $repo_path${NC}"
      continue
    fi

    echo -e "${GREEN}Updating $name clone...${NC}"
    if ! (cd "$repo_path" && git up); then
      echo -e "${YELLOW}git up failed for $name at $repo_path; continuing with existing checkout${NC}"
    fi

    skill_path="$repo_path/$skill_relative_path"
    if [ ! -f "$skill_path/SKILL.md" ]; then
      echo -e "${YELLOW}Skipping $name; $skill_path/SKILL.md was not found${NC}"
      continue
    fi

    link_skill "$name" "$skill_path" "$HOME/.codex/skills"
    link_skill "$name" "$skill_path" "$HOME/.claude/skills"
    run_skill_install_command "$name" "$repo_path" "$install_command"
  done
}

echo -e "${BLUE}Agent Docs Installer${NC}"
echo -e "${BLUE}====================${NC}"
echo

# 1. Install slash commands
echo -e "${GREEN}Installing slash commands...${NC}"
CLAUDE_COMMANDS_DIR="$HOME/.claude/commands"
mkdir -p "$CLAUDE_COMMANDS_DIR"

if [ -d "$SCRIPT_DIR/commands" ]; then
  cp "$SCRIPT_DIR/commands"/*.md "$CLAUDE_COMMANDS_DIR/" 2>/dev/null || {
    echo -e "${YELLOW}No command files found${NC}"
  }
  count=$(find "$CLAUDE_COMMANDS_DIR" -name "*.md" -type f 2>/dev/null | wc -l | tr -d ' ')
  echo -e "${GREEN}✓ Installed $count commands${NC}"
fi

# 2. Link consolidated agent instructions and remove old file names
link_agents_file "$HOME/.config/AGENTS.md"
link_agents_file "$HOME/.codex/AGENTS.md"
remove_legacy_agent_file "$HOME/.claude/CLAUDE.md"
remove_legacy_agent_file "$HOME/.config/AGENT.md"

# 3. Optional: Install tool settings
link_settings claude "$HOME/.claude/settings.json"
link_settings amp "$HOME/.config/amp/settings.json"
link_settings droid "$HOME/.factory/settings.json"
merge_settings claude-mcp "$HOME/.claude.json"

# 4. External skills managed from source clones
install_external_skills

# Done
echo -e "\n${GREEN}✅ Installation complete!${NC}"
echo
echo -e "Commands installed to: ${BLUE}~/.claude/commands/${NC}"
echo -e "Agents config: ${BLUE}~/.config/AGENTS.md${NC}"
echo -e "Codex config: ${BLUE}~/.codex/AGENTS.md${NC}"
echo -e "Codex skills: ${BLUE}~/.codex/skills/${NC}"
echo -e "Claude skills: ${BLUE}~/.claude/skills/${NC}"
echo -e "\nType ${BLUE}/${NC} in Claude Code to see available commands"
