#! /bin/zsh

source /usr/local/Cellar/antigen/2.2.3/share/antigen/antigen.zsh

# Load the oh-my-zsh's library.
antigen use oh-my-zsh

# Bundles from the default repo (robbyrussell's oh-my-zsh).
antigen bundle git
antigen bundle kubectl
antigen bundle brew
antigen bundle shrink-path
antigen bundle command-not-found

# Bundles from the other repos.
antigen bundle caarlos0/zsh-git-sync
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-completions
antigen bundle zsh-users/zsh-autosuggestions

# Bundles for tab completion
antigen bundle zpm-zsh/ssh 
# antigen bundle eastokes/aws-plugin-zsh

# Load the theme.
antigen theme af-magic

# Tell Antigen that you're done.
antigen apply
