#! /bin/zsh

# export TF_PLUGIN_CACHE_DIR=~/.terraform.d/plugin-cache
# Gotta go fast
export TF_CLI_ARGS_plan="-parallelism=100"
export TF_CLI_ARGS_apply="-parallelism=100"
export TF_CLI_ARGS_refresh="-parallelism=100"
export TF_CLI_ARGS_import="-parallelism=100"

alias t='terraform'
alias iterraform='/usr/local/bin/terraform' # x86_64
alias tdocs='terraform-docs markdown . > README.md' # TODO: rework

# tf-wrapper.sh
export PATH=$PATH:$HOME/dev/gcp-projects/modules/cicd

function tvalidate() {
  terraform fmt
  terraform validate
}
