#! /bin/zsh

export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/shims:$PATH"

export PYENV_VIRTUALENV_DISABLE_PROMPT=1 # The prompt is set in zsh_prompt

eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
