#! /bin/zsh

[ -f "$GROQ_CONFIG/zsh/bake-completion.zsh" ] && . "$GROQ_CONFIG/zsh/bake-completion.zsh"
[ -f "$GROQ_CONFIG/zsh/gr-completion.zsh" ] && . "$GROQ_CONFIG/zsh/gr-completion.zsh"
[ -f "$GROQ_CONFIG/zsh/nix.zsh" ] && . "$GROQ_CONFIG/zsh/nix.zsh"
