#! /bin/zsh

[ -f "$GROQ_CONFIG/zsh/bake-completion.zsh" ] && . "$GROQ_CONFIG/zsh/bake-completion.zsh"
[ -f "$GROQ_CONFIG/zsh/gr-completion.zsh" ] && . "$GROQ_CONFIG/zsh/gr-completion.zsh"
[ -f "$GROQ_CONFIG/zsh/nix.zsh" ] && . "$GROQ_CONFIG/zsh/nix.zsh"
[ -f "$GROQ_CONFIG/zsh/fix-sft.zsh" ] && . "$GROQ_CONFIG/zsh/fix-sft.zsh"
# ssh X tmux
alias attach="sft ssh --via asabastion-northamerica-northeast2.groq.net --command \"tmux -CC new -As0\""

function refresh () {
  if [ -n "$TMUX" ]; then
    eval $(tmux showenv -s)
  fi
}
autoload -Uz refresh
function preexec {
  refresh
}
