#! /bin/zsh

function iTermSetKube {
  local curcontext=""
  local curkube=""
  local curnamespace=""
  local curdir=""
  local curdatetime=""
  local dispkube=""
  local promptcolour=""
  local cloud_details=""

  PYENV_PROMT=""
  KUBERNETES_PROMPT=""
  CLOUD_PROMPT=""
  DATE_TIME_PROMPT=""

  # run `spectrum_ls` to see all colours
  local light_colour=$FG[008]
  local prompt_separator="${light_colour}-----%{$reset_color%}"

  setPyenvPrompt
  setKubernetesPrompt
  setCloudPrompt
  setDateTimePrompt
}

function setPyenvPrompt {
  if [ -n "${PYENV_VERSION}" ]; then
    export PYENV_PROMPT="$FG[172][${PYENV_VERSION}]%{$reset_color%} ${prompt_separator}"
  fi
}

function setKubernetesPrompt {
  if kubectl config current-context > /dev/null 2>&1; then
    curcontext=$(kubectl config get-contexts `kubectl config current-context`)
    curkube=$(echo ${curcontext} | grep "^*" | awk '{print $2}' | cut -d '.' -f 1)
    curnamespace=$(echo ${curcontext} | grep '^*' | perl -p -e 's/^\*\s+\S+\s+\S+\s+\S+\s+(\S*)$/$1/g')

    # COMMON
    [[ "${curkube}" =~ "gke-c.*" ]] && promptcolour=$FG[005]
    # DEV
    [[ "${curkube}" =~ "gke-d-.*" ]] && promptcolour=$FG[002]
    [[ "${curkube}" =~ "gke-x-.*" ]] && promptcolour=$FG[002]
    # STAGING
    [[ "${curkube}" =~ "gke-s-.*" ]] && promptcolour=$FG[032]
    # PROD
    [[ "${curkube}" =~ "gke-p-.*" ]] && promptcolour=$FG[001]

    export KUBERNETES_PROMPT="${promptcolour}${curkube} | ${curnamespace}%{$reset_color%} ${prompt_separator} "
  fi
}

function setCloudPrompt {
  if [ -f "${HOME}/.config/gcloud/configurations/config_default" ]; then
    # gcp_project=$(gcloud config get-value project)
    gcp_project=$(cat "${HOME}/.config/gcloud/configurations/config_default" | grep project | awk '{print $3}')
    cloud_details="${gcp_project}"
    export CLOUD_PROMPT="${light_colour}${cloud_details}%{$reset_color%} ${prompt_separator} "
  fi
}

function setDateTimePrompt {
  curdatetime=$(date -u '+%Y-%m-%d %H:%M:%S')
  export DATE_TIME_PROMPT="${light_colour}${curdatetime}%{$reset_color%} ${prompt_separator} "
}

function iTermSetTitle {
	local curproject=""
	local curdir=$(print -P %~)

	if [[ $curdir = "~/dev/"* ]]
	then
		curproject=`echo $curdir/ | perl -p -e 's#^.*/dev/(\S+?)/.*$#$1#g'`
	else
		curproject=${curdir: -12}
	fi
	echo -n -e "\e]1;${curproject}\a"
}

function restoreprompt {
    export PROMPT='${PYENV_PROMPT}${KUBERNETES_PROMPT}${CLOUD_PROMPT}${DATE_TIME_PROMPT}
$FG[032]%~\
$(git_prompt_info) \
$FG[105]%(!.#.»)%{$reset_color%} '
    export RPROMPT=""
}

function truncateprompt {
    export PROMPT='${KUBERNETES_PROMPT}${CLOUD_PROMPT}${DATE_TIME_PROMPT}
$FG[032]$(shrink_path -t -l)\
$(git_prompt_info) \
$FG[105]%(!.#.»)%{$reset_color%} '
    export RPROMPT=""
}

precmd() {
    iTermSetKube
    iTermSetTitle
}

restoreprompt
