#! /bin/zsh

export PYENV_ROOT="$HOME/.pyenv"
if [[ $(uname) == "Darwin" ]]; then
  export PATH="$PYENV_ROOT/shims:$PATH"
else
  export PATH="$PYENV_ROOT/bin:$PATH"
fi

export PYENV_VIRTUALENV_DISABLE_PROMPT=1 # The prompt is set in zsh_prompt

# TODO: These are slow
# These will be replaced with hermit soon
# eval "$(pyenv init -)"
# eval "$(pyenv virtualenv-init -)"
