#! /bin/zsh

alias g='gcloud'
alias glogin='gcloud auth login --brief --launch-browser --update-adc'

function gcurl () {
  local token=$(gcloud auth print-access-token)
  curl --header "Authorization: Bearer $token" $@
}

export CLOUDSDK_PYTHON="/Users/reid/.pyenv/shims/python3.9"
export CLOUDSDK_PYTHON_SITEPACKAGES=1

[ -f '/Users/reid/bin/google-cloud-sdk/path.zsh.inc' ] && . '/Users/reid/bin/google-cloud-sdk/path.zsh.inc'
[ -f '/Users/reid/bin/google-cloud-sdk/completion.zsh.inc' ] && . '/Users/reid/bin/google-cloud-sdk/completion.zsh.inc'
