#! /bin/zsh

if [[ "$VSCODE_INJECTION" == "1" ]]; then
  rm -f "$HOME/.zsh/.vscode_env"
  for i in $(env | grep VSCODE); do
    echo "export $i" >> "$HOME/.zsh/.vscode_env"
  done
else
  # Prevent an error when we source this file
  touch "$HOME/.zsh/.vscode_env"
fi

# Always source this in case the values have changed
. "$HOME/.zsh/.vscode_env"

vscode_path="$(dirname $VSCODE_GIT_ASKPASS_NODE)/bin/remote-cli"
PATH="$vscode_path:$PATH"
