#! /bin/zsh

export HOMEBREW_NO_ENV_HINTS=true

if [[ -x /opt/homebrew/bin/brew ]]; then
  my_brew="/opt/homebrew/bin/brew"
else
  my_brew=$(which brew)
fi

eval "$(${my_brew} shellenv)"

brew_completion=$(brew --prefix 2>/dev/null)/share/zsh/site-functions
if [ $? -eq 0 ] && [ -d "$brew_completion" ];then
  fpath=($brew_completion $fpath)
fi
autoload -U compinit
compinit
