#! /bin/zsh

if [[ $(uname) == "Linux" ]]; then
  export VSCODE_SERVER=$(ls -td $HOME/.vscode-server/cli/servers/Stable-*[0-9] | head -1)
  # needed to be able to open files in VS Code's editor from the command line
  export VSCODE_IPC_HOOK_CLI="$( ls -td /run/user/$UID/vscode-ipc-*.sock | head -1)"

  PATH="$VSCODE_SERVER/server/bin/remote-cli:$PATH"
fi
