#! /bin/zsh

if (( $+commands[gitleaks] )); then
  eval "$(gitleaks completion zsh)"
fi

function clean-git-branches() {
  declare -a branches=(
    "dev"
    "main"
    "prod"
  )

  local current_branch=$(git branch | sed -n 's/* //p')
  local default_branch=$(git remote show origin | sed -n '/HEAD branch/s/.*: //p')

  git checkout "${default_branch}"

  # Remove deleted branches
  git fetch --prune
  git pull
  git branch -vv | grep 'origin/.*: gone]' | awk '{print $1}' | xargs git branch -D

  for branch in "${branches[@]}" "${default_branch}"; do
    git checkout "${branch}" 2>/dev/null && git reset --hard origin/${branch} || true
  done

  git checkout "${current_branch}" || git checkout "${default_branch}"
}

function hub_repos() {
  local github_org="definitive-io"
  source ~/.secrets/hub

  local page=1 # 1-based pages :(
  local repos=""

  while true; do
    local page_repos=$(hub api /orgs/${github_org}/repos \
      -X GET \
      -f per_page=100 \
      -f page=${page} \
    | jq -r '.[] | select(.archived == false) | .name')

    [[ -z "${page_repos}" ]] && break

    repos="${repos}\n${page_repos}"
    let "page+=1"
  done

  unset GITHUB_TOKEN
  echo "${repos}"
}

function hub_archived_repos() {
  local github_org="definitive-io"
  source ~/.secrets/hub

  local page=1 # 1-based pages :(
  local repos=""

  while true; do
    local page_repos=$(hub api /orgs/${github_org}/repos \
      -X GET \
      -f per_page=100 \
      -f page=${page} \
    | jq -r '.[] | select(.archived == true) | .name')

    [[ -z "${page_repos}" ]] && break

    repos="${repos}\n${page_repos}"
    let "page+=1"
  done

  unset GITHUB_TOKEN
  echo "${repos}"
}

function clone-all-repos() {
  local github_org="definitive-io"

  pushd ~/dev > /dev/null

  for repo in $(hub_repos); do
    if [[ ! -d "${repo}" ]]; then
      git clone "git@github.com:${github_org}/${repo}.git"
    fi
  done

  popd > /dev/null
}

function update-all-repos() {
  pushd ~/dev > /dev/null

  for repo in $(ls); do
    if [[ -d "${repo}" ]]; then
      echo $repo
      pushd "${repo}" > /dev/null
      clean-git-branches
      popd > /dev/null
      echo
    fi
  done

  popd > /dev/null
}

function remove-archived-repos() {
  local github_org="definitive-io"

  pushd ~/dev > /dev/null

  for repo in $(hub_archived_repos); do
    if [[ -d "${repo}" ]]; then
      rm -rfv "${repo}"
    fi
  done

  popd > /dev/null
}
