#! /bin/zsh

##### run `spectrum_ls` to see all colours #####
function iTermSetPromptHeader {
  local curcontext=""
  local curkube=""
  local curnamespace=""
  local curdir=""
  local curdatetime=""
  local dispkube=""
  local promptcolour=""
  local cloud_details=""

  PYENV_PROMPT=""
  KUBERNETES_PROMPT=""
  CLOUD_PROMPT=""
  DATE_TIME_PROMPT=""

  local light_colour=$FG[008]
  local prompt_separator="${light_colour}-----%{$reset_color%}"

  setTerraformPrompt
  setPyenvPrompt
  setKubernetesPrompt
  setCloudPrompt
  # setDateTimePrompt
}

function setTerraformPrompt {
  local tf_workspace
  tf_workspace=$(terraform workspace show 2>/dev/null)
  if [[ "${tf_workspace}" = "default" ]]; then
    export TF_PROMPT=""
  else
    export TF_PROMPT="$FG[207](${tf_workspace})%{$reset_color%} ${prompt_separator} "
  fi
}

function setPyenvPrompt {
  if [[ -n "${PYENV_VERSION}" ]]; then
    export PYENV_PROMPT="$FG[172][${PYENV_VERSION}]%{$reset_color%} ${prompt_separator} "
  fi
}

function setKubernetesPrompt {
  if kubectl config current-context > /dev/null 2>&1; then
    local curcontext=$(kubectl config get-contexts $(kubectl config current-context))
    local curkube=$(echo ${curcontext} | grep "^*" | awk '{print $2}' | cut -d '.' -f 1 | perl -pe 's/.*_(.*?)/$1/g' | perl -pe 's/^us-central1-//g')
    local curnamespace=$(echo ${curcontext} | grep '^*' | perl -p -e 's/^\*\s+\S+\s+\S+\s+\S+\s+(\S*)$/$1/g')
    local proxy_enabled=""

    # COMMON
    [[ "${curkube}" =~ ".*-c.*" ]] && promptcolour=$FG[005]
    # DEV
    [[ "${curkube}" =~ ".*-d-.*" ]] && promptcolour=$FG[002]
    [[ "${curkube}" =~ ".*-x-.*" ]] && promptcolour=$FG[002]
    # STAGING
    [[ "${curkube}" =~ ".*-s-.*" ]] && promptcolour=$FG[003]
    # PROD
    [[ "${curkube}" =~ ".*-p-.*" ]] && promptcolour=$FG[001]

    if [[ -n "${HTTPS_PROXY}" ]]; then
      proxy_enabled="{*} "
    fi

    export KUBERNETES_PROMPT="${promptcolour}${proxy_enabled}${curkube} | ${curnamespace}%{$reset_color%} ${prompt_separator} "
  fi
}

function setCloudPrompt {
  if [ -f "${HOME}/.config/gcloud/configurations/config_default" ]; then
    local gcloud_profile=$(gcloud config configurations list --filter='is_active:True' --format json | jq -r '.[].name')
    local gcloud_project=$(g config list --format json | jq -r '.core.project')
    # local gcloud_project=$(gcloud config get-value project)
    local cloud_details="[${gcloud_profile}] ${gcloud_project}"
    export CLOUD_PROMPT="${light_colour}${cloud_details}%{$reset_color%} ${prompt_separator} "
  fi
}

function setDateTimePrompt {
  curdatetime=$(date -u '+%Y-%m-%d %H:%M:%S')
  export DATE_TIME_PROMPT="${light_colour}${curdatetime}%{$reset_color%} ${prompt_separator} "
}

function iTermSetTitle {
	local curproject=""
	local curdir=$(print -P %~)

	if [[ $curdir = "~/dev/"* ]]
	then
		curproject=`echo $curdir/ | perl -p -e 's#^.*/dev/(\S+?)/.*$#$1#g'`
	else
		curproject=${curdir: -12}
	fi
	echo -n -e "\e]1;${curproject}\a"
}

function setprompt {
  export PROMPT='${TF_PROMPT}${PYENV_PROMPT}${KUBERNETES_PROMPT}${CLOUD_PROMPT}${DATE_TIME_PROMPT}
$FG[032]%~\
$(git_prompt_info) \
%(?..%B[%?%\]%b )\
$FG[105]%(!.#.»)%{$reset_color%} '
  export RPROMPT=""
}

precmd() {
    iTermSetPromptHeader
    iTermSetTitle
}

setprompt
