#! /bin/zsh

# Aliases
alias kc="kubectl"
alias kcg="kc get -o yaml"
#alias kcd="kc describe"
alias kcpf="kc port-forward"
alias kclogs="kc logs -f "
alias kcpods="kc get pods | grep "
alias kcsecrets="kc get secrets | grep "
# alias kcwatch="watch 'kubectl get pod | grep'"
alias port-forward-prometheus='kc port-forward service/prometheus-server -n monitoring 9090:80'
alias port-forward-alertmanager='kubectl port-forward service/prometheus-alertmanager -n monitoring 9093:80'
alias kcnodes="kc get node  --sort-by=.metadata.creationTimestamp"

# Remove alias from kubectl plugin
unalias kcp
unalias ksd
unalias kca

# Functions
function kcgb() {
  typeset RESOURCE_TYPE=$1
  typeset SERVICE_NAME=$2

  kubectl get -o yaml $RESOURCE_TYPE $SERVICE_NAME | bat -lyaml
}

function kss() {
  typeset SERVICE_NAME=$1
  typeset REPLICAS=$2
  kubectl scale statefulset $SERVICE_NAME --replicas=$REPLICAS
}

function ksd() {
  typeset SERVICE_NAME=$1
  typeset REPLICAS=$2
  kubectl scale deployment $SERVICE_NAME --replicas=$REPLICAS
}

function getsecretvalue() {
  typeset SECRET_NAME=$1
  typeset LITERAL_KEY=$2
  kubectl get secrets $SECRET_NAME -o yaml | grep $LITERAL_KEY | cut -d ":" -f 2 | tr -d ' ' | base64 --decode
}

function getsecret() {
  typeset SECRET_NAME=$1
  kubectl get secrets $SECRET_NAME -o yaml
}

function kcwatch() {
  typeset RESOURCE_TYPE=$1
  typeset REGEX=${2:-}

  watch "kubectl get ${RESOURCE_TYPE} | grep \"${REGEX}\""
}

function kcwatchnodes() {
  local GROUP=${1:-nodes}
  local COLUMN=${2:-zone}

  watch "kubectl get node --sort-by=.metadata.creationTimestamp -l autonomic.ai/type=${GROUP} --show-labels | perl -p -e \"s/autonomic.ai.*beta.kubernetes.io\/${COLUMN}=(.*?),.*/\\\$1/g\""
}
