#! /bin/zsh

if (( $+commands[gitleaks] )); then
  eval "$(gitleaks completion zsh)"
fi

unalias gr

function gk() {
  groqkite gh "$@" --key-file=~/.secrets/groqkite.private-key.pem
}

function clean-git-branches() {
  declare -a branches=(
    "dev"
    "main"
    "prod"
    "head"
  )

  local current_branch=$(git branch | sed -n 's/* //p')
  local default_branch=$(git remote show origin | sed -n '/HEAD branch/s/.*: //p')

  git checkout "${default_branch}"

  # Remove deleted branches
  git fetch --prune
  git pull
  for branch in $(git branch -vv | grep 'origin/.*: gone]' | awk '{print $1}'); do
    git branch -D "${branch}"
  done

  for branch in "${branches[@]}" "${default_branch}"; do
    git checkout "${branch}" 2>/dev/null && git reset --hard origin/${branch} || true
  done

  git checkout "${current_branch}" || git checkout "${default_branch}"
}

function groq_repos() {
  local github_org="groq"

  local page=1 # 1-based pages :(
  local repos=""

  while true; do
    local page_repos=$(gh api /orgs/${github_org}/repos \
      -X GET \
      -f per_page=100 \
      -f page=${page} \
    | jq -r '.[] | select(.archived == false) | .name')

    [[ -z "${page_repos}" ]] && break

    repos="${repos}\n${page_repos}"
    let "page+=1"
  done

  echo "${repos}"
}

function groq_archived_repos() {
  local github_org="groq"

  local page=1 # 1-based pages :(
  local repos=""

  while true; do
    local page_repos=$(gh api /orgs/${github_org}/repos \
      -X GET \
      -f per_page=100 \
      -f page=${page} \
    | jq -r '.[] | select(.archived == true) | .name')

    [[ -z "${page_repos}" ]] && break

    repos="${repos}\n${page_repos}"
    let "page+=1"
  done

  echo "${repos}"
}

function clone-all-repos() {
  local github_org="groq"

  pushd ~/dev > /dev/null

  for repo in $(groq_repos); do
    if [[ ! -d "${repo}" ]]; then
      git clone "git@github.com:${github_org}/${repo}.git"
    fi
  done

  popd > /dev/null
}

function update-all-repos() {
  pushd ~/dev > /dev/null

  for repo in $(ls); do
    if [[ -d "${repo}" ]]; then
      echo $repo
      pushd "${repo}" > /dev/null
      clean-git-branches
      popd > /dev/null
      echo
    fi
  done

  popd > /dev/null
}

function prune-repos() {
  local github_org="groq"

  pushd ~/dev > /dev/null

  for repo in $(groq_archived_repos); do
    if [[ -d "${repo}" ]]; then
      echo "Deleting ${repo}"
      rm -rf "${repo}"
    fi
  done

  popd > /dev/null
}

function gr {
    local flags=(
        --slack
        --update-mr
        --ci-start
    )
    local extras=()
    case $1 in
    # push) extras=(--label ReleaseUpdate::NotRequired --ci-start);;
    push) extras=(--ci-start);;
    mr-get) extras=(--format=short)
    esac
    SFT_AUTH_SOCK= command gr $flags $extras "$@"
}
