#! /bin/zsh

# Aliases
# alias kubectl='HTTPS_PROXY=socks5://127.0.0.1:8444 kubectl'
# alias kubectx='HTTPS_PROXY=socks5://127.0.0.1:8444 kubectx'
# alias kubens='HTTPS_PROXY=socks5://127.0.0.1:8444 kubens'
# alias nomos='HTTPS_PROXY=socks5://127.0.0.1:8444 nomos'
# alias stern='HTTPS_PROXY=socks5://127.0.0.1:8444 stern'

alias kx='kubectx'
alias kn='kubens'
alias kg="k get -o yaml"
alias kpf="k port-forward"
alias kpods="k get pods | grep "
alias ksecrets="k get secrets | grep "
alias port-forward-prometheus='k port-forward service/prometheus-server -n monitoring 9090:80'
alias port-forward-alertmanager='k port-forward service/prometheus-alertmanager -n monitoring 9093:80'
alias knodes="k get node  --sort-by=.metadata.creationTimestamp"

[[ -f ~/dev/ops-tools/kube/definitive-kuberc.sh ]] && source ~/dev/ops-tools/kube/definitive-kuberc.sh

export USE_GKE_GCLOUD_AUTH_PLUGIN=True


# Functions
# function kproxy() {
#   local ON_OFF=${1:-"on"}

#   if [[ "${ON_OFF}" == "on" ]]; then
#     export HTTPS_PROXY=socks5://127.0.0.1:8444
#   else
#     unset HTTPS_PROXY
#   fi
# }

# function ksetup() {
#   local ENV_CODE=${1:-d}
#   local BU=${2:-gencomp}
#   local PORT=${3:-8444}

#   local PROJECT=$(gcloud projects list | grep prj-${ENV_CODE}-${BU}-gke | awk '{print $1}')
#   local CLUSTER_INFO=$(gcloud container clusters list --project "${PROJECT}" | grep gke-${ENV_CODE}-)
#   local CLUSTER=$(echo "$CLUSTER_INFO" | awk '{print $1}')
#   local CLUSTER_REGION=$(echo "$CLUSTER_INFO" | awk '{print $2}')

#   gcloud container clusters get-credentials "${CLUSTER}" \
#     --project "${PROJECT}" \
#     --region "${CLUSTER_REGION}"

#   local BASTION_INFO=$(gcloud compute instances list --project "${PROJECT}" | grep gce-bastion)
#   local BASTION=$(echo "${BASTION_INFO}" | awk '{print $1}')
#   local BASTION_ZONE=$(echo "${BASTION_INFO}" | awk '{print $2}')

#   echo "Establishing IAP tunnel to ${BASTION}"
#   gcloud compute ssh "${BASTION}" \
#     --tunnel-through-iap \
#     --ssh-flag="-ND ${PORT}" \
#     --project "${PROJECT}" \
#     --zone "${BASTION_ZONE}" &
#   echo "Established IAP tunnel to ${BASTION}"
#   fg
# }

function kgb() {
  typeset RESOURCE_TYPE=$1
  typeset SERVICE_NAME=$2

  kubectl get -o yaml $RESOURCE_TYPE $SERVICE_NAME | bat -lyaml
}

function kss() {
  typeset SERVICE_NAME=$1
  typeset REPLICAS=$2
  kubectl scale statefulset $SERVICE_NAME --replicas=$REPLICAS
}

function ksd() {
  typeset SERVICE_NAME=$1
  typeset REPLICAS=$2
  kubectl scale deployment $SERVICE_NAME --replicas=$REPLICAS
}

function getsecretvalue() {
  typeset SECRET_NAME=$1
  typeset LITERAL_KEY=$2
  kubectl get secrets $SECRET_NAME -o yaml | grep $LITERAL_KEY | cut -d ":" -f 2 | tr -d ' ' | base64 --decode
}

function getsecret() {
  typeset SECRET_NAME=$1
  kubectl get secrets $SECRET_NAME -o yaml
}

function kwatch() {
  typeset RESOURCE_TYPE=$1; shift;
  typeset REGEX=${*:-}

  watch "kubectl get ${RESOURCE_TYPE} | grep ${REGEX}"
}

function kwatchnodes() {
  local GROUP=${1:-nodes}
  local COLUMN=${2:-zone}

  watch "kubectl get node --sort-by=.metadata.creationTimestamp -l autonomic.ai/type=${GROUP} --show-labels | perl -p -e \"s/autonomic.ai.*beta.kubernetes.io\/${COLUMN}=(.*?),.*/\\\$1/g\""
}

function kpsp() {
  local template=$'{{range .items}}{{if .metadata.annotations }}{{ if (index .metadata.annotations "kubernetes.io/psp")}} {{printf "%-80s %s\\n" .metadata.name (index .metadata.annotations "kubernetes.io/psp" )}}{{end}}{{end}}{{end}}'
  printf "%-80s %s" POD_NAME SECURITY_POLICY
  echo ""
  kubectl get pods --output go-template="${template}" $*
}
