#! /bin/zsh

# Local Variables
ZSHRC_TIMING_INFO=false
ZSHRC_TIMING_DATE_CMD=/opt/homebrew/bin/gdate
if [[ ! -f "${ZSHRC_TIMING_DATE_CMD}" ]]; then
  ZSHRC_TIMING_DATE_CMD=date
fi
ZSHRC_PROFILE=false
if [[ "${ZSHRC_PROFILE}" = true ]]; then
  zmodload zsh/zprof
fi

# Path-Setters
# We need to load these before ohmyzshrc so that the PATH is set correctly for the plugins
do_source() {
  local file=$1
  if [[ "${ZSHRC_TIMING_INFO}" = true ]]; then
    local start_time=$(${ZSHRC_TIMING_DATE_CMD} +%s.%N)
    source "$file"
    local end_time=$(${ZSHRC_TIMING_DATE_CMD} +%s.%N)
    local total_time_ms=$(bc -l <<< "($end_time - $start_time) * 1000")
    printf "Sourced %s in %.3f ms\n" "$file" "$total_time_ms"
  else
    source "$file"
  fi
}

do_source $HOME/.zsh/zsh_vscode
do_source $HOME/.zsh/zsh_brew # keep this first
do_source $HOME/.zsh/zsh_path

# Oh My Zsh
do_source $HOME/.zsh/ohmyzshrc # 200ms

# Language Specific Files
do_source $HOME/.zsh/zsh_gcp
do_source $HOME/.zsh/zsh_kubernetes
do_source $HOME/.zsh/zsh_terraform
do_source $HOME/.zsh/zsh_git
do_source $HOME/.zsh/zsh_pnpm
do_source $HOME/.zsh/zsh_iterm
do_source $HOME/.zsh/zsh_haskell
do_source $HOME/.zsh/zsh_groq
do_source $HOME/.zsh/zsh_ruby
do_source $HOME/.zsh/zsh_aider
do_source $HOME/.zsh/zsh_task
do_source $HOME/.zsh/zsh_nix

# These are slow :(
do_source $HOME/.zsh/zsh_hermit

# General Purpose Files
do_source $HOME/.zsh/zsh_functions
do_source $HOME/.zsh/zsh_aliases
do_source $HOME/.zsh/zsh_prompt
do_source $HOME/.zsh/zsh_environ

# Keep history per shell (i.e. don't share)
#setopt noincappendhistory
#setopt nosharehistory

# Keep this last
do_source $HOME/.zsh/zsh_precmd

# Unset local variables
unset ZSHRC_TIMING_INFO
unset ZSHRC_TIMING_DATE_CMD
unset ZSHRC_PROFILE

# Generated by Groq bootstrap; START; DO NOT EDIT.
# Version: 20240128
export PATH="/Users/reid/.local/share/hermit/bin:$PATH"

# Hermit shell hooks
change_hermit_env() {
  local CUR=${PWD}
  while [ "$CUR" != "/" ]; do
    if [ "${CUR}" -ef "${HERMIT_ENV}" ]; then return; fi
    if [ -f "${CUR}/bin/activate-hermit" ]; then
      if [ -n "${HERMIT_ENV+_}"  ]; then type _hermit_deactivate &>/dev/null && _hermit_deactivate; fi
      # shellcheck source=files/activate-hermit
      if ! [ "${CUR}" -ef "${DEACTIVATED_HERMIT}" ]; then
        if "${HERMIT_ROOT_BIN:-"$HOME/bin/hermit"}" --quiet validate env "${CUR}"; then
          . "${CUR}/bin/activate-hermit"
        fi
      fi
      return
    fi
    CUR="$(dirname "${CUR}")"
  done
  unset DEACTIVATED_HERMIT
  if [ -n "${HERMIT_ENV+_}"  ]; then type _hermit_deactivate &>/dev/null && _hermit_deactivate; fi
}

precmd_functions+=(change_hermit_env)

# shellcheck disable=SC2154
if [[ -n ${_comps+x} ]]; then
  autoload -U +X bashcompinit && bashcompinit
  complete -o nospace -C "${HERMIT_ROOT_BIN:-"$HOME/bin/hermit"} noop" hermit
fi
# Generated by Groq bootstrap; END; DO NOT EDIT.
