#! /bin/zsh

# Local Variables
zshrc_timing_info=false
zshrc_timing_date_cmd=/opt/homebrew/bin/gdate
if [[ ! -f "${zshrc_timing_date_cmd}" ]]; then
  zshrc_timing_date_cmd=date
fi
zshrc_profile=false
if [[ "${zshrc_profile}" = true ]]; then
  zmodload zsh/zprof
fi

# Path-Setters
# We need to load these before ohmyzshrc so that the PATH is set correctly for the plugins
do_source() {
  local file=$1
  if [[ "${zshrc_timing_info}" = true ]]; then
    local start_time=$(${zshrc_timing_date_cmd} +%s.%N)
    source "$file"
    local end_time=$(${zshrc_timing_date_cmd} +%s.%N)
    local total_time_ms=$(bc -l <<< "($end_time - $start_time) * 1000")
    printf "Sourced %s in %.3f ms\n" "$file" "$total_time_ms"
  else
    source "$file"
  fi
}

do_source $HOME/.zsh/zsh_vscode
do_source $HOME/.zsh/zsh_brew # keep this first
do_source $HOME/.zsh/zsh_path

# Oh My Zsh
do_source $HOME/.zsh/ohmyzshrc # 200ms

# Language Specific Files
do_source $HOME/.zsh/zsh_gcp
do_source $HOME/.zsh/zsh_kubernetes
do_source $HOME/.zsh/zsh_terraform
do_source $HOME/.zsh/zsh_git
do_source $HOME/.zsh/zsh_pnpm
do_source $HOME/.zsh/zsh_iterm
do_source $HOME/.zsh/zsh_haskell
do_source $HOME/.zsh/zsh_groq
do_source $HOME/.zsh/zsh_ruby
do_source $HOME/.zsh/zsh_aider
do_source $HOME/.zsh/zsh_task
do_source $HOME/.zsh/zsh_nix

# These are slow :(
do_source $HOME/.zsh/zsh_hermit

# General Purpose Files
do_source $HOME/.zsh/zsh_functions
do_source $HOME/.zsh/zsh_aliases
do_source $HOME/.zsh/zsh_prompt
do_source $HOME/.zsh/zsh_environ

# Keep history per shell (i.e. don't share)
#setopt noincappendhistory
#setopt nosharehistory

# Keep this last
do_source $HOME/.zsh/zsh_precmd
# Generated by Groq bootstrap; START; DO NOT EDIT.
source $HOME/.config/groq-bootstrap/groq-bootstrap.zsh
# Generated by Groq bootstrap; END; DO NOT EDIT.
